### ISSUE TITLE
Discuss the results returned from calling hooks

### ISSUE THREAD

**Issue by tlambert03** [napari/napari-plugin-engine#12]
#10 addressed an immediate need we had in napari/napari#2080 ... but it's worth having a discussion about whether we should make a larger break from the standard pluggy return value (that lacks information about _which_ plugin provided the value), and standardize a different API

**Comment by jni** [comment]
The more I read the pluggy docs (see my [comment](https://github.com/napari/napari/pull/2080#discussion_r553135893) about `historic`), the less inclined I am to stick to their existing conventions. So 👍 from me.
