### ISSUE TITLE
migrate pypi code from napari core repo to plugin engine

### ISSUE THREAD

**Issue by ziyangczi** [napari/napari-plugin-engine#13]
To facilitate the upcoming alpha cohort of plugin development, I am looking into building some basic functions and infrastructure for plugin devs to quickly check the validity of their on-going dev work. I am thinking we should move the checks from the main repo (https://github.com/napari/napari/blob/master/napari/plugins/pypi.py )to the plugin engine to aggregate the checks to one place, the end goal is to provide developers access to a command-line or pytest module that they can use to test their setup in the same way as plugin engine does, without importing the napari core. thoughts?

**Comment by tlambert03** [comment]
sounds good to me

**Comment by tlambert03** [comment]
maybe the only caveat I can think of is the occasional annoyance of having to coordinate version bumps of related packages, so I also wouldn't mind if we just copied those functions into this package (if you wanted to build off of them to provide dev tools), but maybe also leave them "vendored" in napari as well?  (could be persuaded against that though too)

**Comment by jni** [comment]
The coordinated version bumps are definitely an issue, but one that I think already exists, so it's unclear to me whether this proposal would make things worse?

**Comment by sofroniewn** [comment]
> The coordinated version bumps are definitely an issue, but one that I think already exists, so it's unclear to me whether this proposal would make things worse?

I think the plan is that we'd copy the code over for now, but then after the next `npe` release we'd remove the code from napari and use it from here?
